```mermaid
flowchart LR
    classDef kstart fill:#7ab8ff,stroke:#2563eb,color:#0b1220;
    classDef kdone  fill:#86efac,stroke:#16a34a,color:#052e16;
    classDef kend   fill:#fca5a5,stroke:#dc2626,color:#450a0a;

    n___start((("▶ START")))
    n___start:::kstart
    subgraph sg_all["all"]
    n_accept["accept"]
    n_apartment_bedroom_intro["apartment_bedroom_intro"]
    n_apartment_start["apartment_start"]
    n_archive_shelves_interact["archive_shelves_interact"]
    n_awareness_start["awareness_start"]
    n_bar_counter_interact["bar_counter_interact"]
    n_bathroom_exit_locked["bathroom_exit_locked"]
    n_bathroom_not_now["bathroom_not_now"]
    n_bathroom_sink_prompt["bathroom_sink_prompt"]
    n_bedroom_desk_morning["bedroom_desk_morning"]
    n_cafe_backroom_board_interact["cafe_backroom_board_interact"]
    n_cafe_backroom_books_interact["cafe_backroom_books_interact"]
    n_cafe_backroom_coatrack_interact["cafe_backroom_coatrack_interact"]
    n_cafe_backroom_mirror_interact["cafe_backroom_mirror_interact"]
    n_cafe_bar_interact["cafe_bar_interact"]
    n_cafe_bar_interact_right_place["cafe_bar_interact_right_place"]
    n_cafe_bar_interact_wrong_place["cafe_bar_interact_wrong_place"]
    n_cafe_corner_main_talk["cafe_corner_main_talk"]
    n_cafe_corner_shelf_interact["cafe_corner_shelf_interact"]
    n_cafe_corner_table_interact["cafe_corner_table_interact"]
    n_cafe_corner_window_interact["cafe_corner_window_interact"]
    n_cafe_hall_light_interact["cafe_hall_light_interact"]
    n_cafe_window_table["cafe_window_table"]
    n_choose_character["choose_character"]
    n_day_start["day_start"]
    n_doubt["doubt"]
    n_ending_break["ending_break"]
    n_ending_merge["ending_merge"]
    n_ending_stay["ending_stay"]
    n_endings_start["endings_start"]
    n_enter_bathroom_morning_first["enter_bathroom_morning_first"]
    n_enter_kitchen_morning_first["enter_kitchen_morning_first"]
    n_find_clue["find_clue"]
    n_global_decl["global decl"]
    n_go_back["go_back"]
    n_inv_apartment_bathroom_use_toothbrush_pasted_on_bathroom_sink["inv_apartment_bathroom_use_toothbrush_pasted_on_bathroom_sink"]
    n_inv_apartment_kitchen_morning_use_mug_on_coffee_setup["inv_apartment_kitchen_morning_use_mug_on_coffee_setup"]
    n_inv_apartment_kitchen_use_mug_on_coffee_setup["inv_apartment_kitchen_use_mug_on_coffee_setup"]
    n_inv_combine_fallback["inv_combine_fallback"]
    n_inv_combine_folder_with_report_page["inv_combine_folder_with_report_page"]
    n_inv_combine_toothbrush_with_toothpaste["inv_combine_toothbrush_with_toothpaste"]
    n_inv_fallback["inv_fallback"]
    n_inv_give_fallback["inv_give_fallback"]
    n_inv_inspect_card["inv_inspect_card"]
    n_inv_inspect_case_file["inv_inspect_case_file"]
    n_inv_inspect_fallback["inv_inspect_fallback"]
    n_inv_inspect_folder["inv_inspect_folder"]
    n_inv_inspect_gift_berry_soda["inv_inspect_gift_berry_soda"]
    n_inv_inspect_gift_chips["inv_inspect_gift_chips"]
    n_inv_inspect_gift_coffee_can["inv_inspect_gift_coffee_can"]
    n_inv_inspect_gift_crackers["inv_inspect_gift_crackers"]
    n_inv_inspect_gift_dark_chocolate["inv_inspect_gift_dark_chocolate"]
    n_inv_inspect_gift_energy_drink["inv_inspect_gift_energy_drink"]
    n_inv_inspect_gift_iced_tea["inv_inspect_gift_iced_tea"]
    n_inv_inspect_gift_keychain_flashlight["inv_inspect_gift_keychain_flashlight"]
    n_inv_inspect_gift_milk_chocolate["inv_inspect_gift_milk_chocolate"]
    n_inv_inspect_gift_nuts["inv_inspect_gift_nuts"]
    n_inv_inspect_gift_paper_napkins["inv_inspect_gift_paper_napkins"]
    n_inv_inspect_gift_small_broom["inv_inspect_gift_small_broom"]
    n_inv_inspect_gift_waffle_bar["inv_inspect_gift_waffle_bar"]
    n_inv_inspect_gift_wet_wipes["inv_inspect_gift_wet_wipes"]
    n_inv_inspect_note["inv_inspect_note"]
    n_inv_inspect_park_trash_cup["inv_inspect_park_trash_cup"]
    n_inv_inspect_phone["inv_inspect_phone"]
    n_inv_inspect_report_page["inv_inspect_report_page"]
    n_inv_inspect_toothbrush["inv_inspect_toothbrush"]
    n_inv_inspect_toothbrush_pasted["inv_inspect_toothbrush_pasted"]
    n_inv_inspect_toothpaste["inv_inspect_toothpaste"]
    n_inv_inspect_water_bottle["inv_inspect_water_bottle"]
    n_inv_office_workspace_give_case_file_on_npc["inv_office_workspace_give_case_file_on_npc"]
    n_inv_office_workspace_use_case_file_on_work_desk_submit["inv_office_workspace_use_case_file_on_work_desk_submit"]
    n_inv_park_hub_use_park_trash_cup_on_park_bin["inv_park_hub_use_park_trash_cup_on_park_bin"]
    n_inv_read_case_file["inv_read_case_file"]
    n_inv_read_fallback["inv_read_fallback"]
    n_inv_read_note["inv_read_note"]
    n_inv_read_report_page["inv_read_report_page"]
    n_inv_use_card_on_fallback["inv_use_card_on_fallback"]
    n_inv_use_case_file_on_fallback["inv_use_case_file_on_fallback"]
    n_inv_use_fallback["inv_use_fallback"]
    n_inv_use_on_fallback["inv_use_on_fallback"]
    n_inv_use_park_trash_cup_on_fallback["inv_use_park_trash_cup_on_fallback"]
    n_inv_work_hub_use_card_on_office_turnstile["inv_work_hub_use_card_on_office_turnstile"]
    n_investigation_start["investigation_start"]
    n_journal_start["journal_start"]
    n_leave_apartment["leave_apartment"]
    n_leave_apartment_prompt["leave_apartment_prompt"]
    n_leave_archive["leave_archive"]
    n_leave_bar["leave_bar"]
    n_leave_cafe["leave_cafe"]
    n_leave_park["leave_park"]
    n_leave_shop["leave_shop"]
    n_leave_viewpoint["leave_viewpoint"]
    n_leave_work["leave_work"]
    n_look_around["look_around"]
    n_look_bathroom_mirror["look_bathroom_mirror"]
    n_look_bed_morning["look_bed_morning"]
    n_look_bedroom_window["look_bedroom_window"]
    n_look_hall_mirror["look_hall_mirror"]
    n_look_kitchen_fridge["look_kitchen_fridge"]
    n_look_kitchen_window["look_kitchen_window"]
    n_loop1_to_iter2_reset["loop1_to_iter2_reset"]
    n_loop2_fake_wednesday_leave_for_work["loop2_fake_wednesday_leave_for_work"]
    n_loop2_fake_wednesday_work_check["loop2_fake_wednesday_work_check"]
    n_loop_entry["loop_entry"]
    n_meeting_room_table_after["meeting_room_table_after"]
    n_meeting_room_take_folder["meeting_room_take_folder"]
    n_mon_commute_entry["mon_commute_entry"]
    n_mon_commute_office_approach["mon_commute_office_approach"]
    n_mon_commute_walk_auto["mon_commute_walk_auto"]
    n_mon_commute_walk_observe["mon_commute_walk_observe"]
    n_mon_commute_walk_steady["mon_commute_walk_steady"]
    n_mon_commute_work_district["mon_commute_work_district"]
    n_mon_home_bed["mon_home_bed"]
    n_mon_home_bedroom_desk["mon_home_bedroom_desk"]
    n_mon_home_bedroom_intro["mon_home_bedroom_intro"]
    n_mon_home_get_dressed["mon_home_get_dressed"]
    n_mon_home_hall_intro["mon_home_hall_intro"]
    n_mon_home_hall_mirror["mon_home_hall_mirror"]
    n_mon_home_kitchen_breakfast["mon_home_kitchen_breakfast"]
    n_mon_home_kitchen_breakfast_after["mon_home_kitchen_breakfast_after"]
    n_mon_home_kitchen_coffee["mon_home_kitchen_coffee"]
    n_mon_home_kitchen_coffee_after["mon_home_kitchen_coffee_after"]
    n_mon_home_kitchen_intro["mon_home_kitchen_intro"]
    n_mon_home_kitchen_water["mon_home_kitchen_water"]
    n_mon_home_kitchen_window["mon_home_kitchen_window"]
    n_mon_home_leave_apartment["mon_home_leave_apartment"]
    n_mon_home_leave_apartment_locked["mon_home_leave_apartment_locked"]
    n_mon_home_take_work_card["mon_home_take_work_card"]
    n_mon_home_wash_up["mon_home_wash_up"]
    n_mon_office_auto_standard["mon_office_auto_standard"]
    n_mon_office_case_router["mon_office_case_router"]
    n_mon_office_clarify["mon_office_clarify"]
    n_mon_office_core_choice["mon_office_core_choice"]
    n_mon_office_day_end["mon_office_day_end"]
    n_mon_office_entry["mon_office_entry"]
    n_mon_office_evening_close["mon_office_evening_close"]
    n_mon_office_manual_standard["mon_office_manual_standard"]
    n_mon_office_npc_greeting["mon_office_npc_greeting"]
    n_mon_office_npc_strange["mon_office_npc_strange"]
    n_mon_office_result_system_bias["mon_office_result_system_bias"]
    n_mon_office_result_true_bias["mon_office_result_true_bias"]
    n_mon_office_stop_auto["mon_office_stop_auto"]
    n_mon_office_system_warning["mon_office_system_warning"]
    n_mon_office_task_intro["mon_office_task_intro"]
    n_monday_morning_start["monday_morning_start"]
    n_msg_artem_loop2_place_choice["msg_artem_loop2_place_choice"]
    n_msg_artem_loop2_place_pressure["msg_artem_loop2_place_pressure"]
    n_msg_mila_loop2_place_choice["msg_mila_loop2_place_choice"]
    n_msg_mila_loop2_place_pressure["msg_mila_loop2_place_pressure"]
    n_msg_npc_place_sent["msg_npc_place_sent"]
    n_msg_thread_artem["msg_thread_artem"]
    n_msg_thread_artem_iter1["msg_thread_artem_iter1"]
    n_msg_thread_artem_loop2["msg_thread_artem_loop2"]
    n_msg_thread_mila["msg_thread_mila"]
    n_msg_thread_mila_iter1["msg_thread_mila_iter1"]
    n_msg_thread_mila_loop2["msg_thread_mila_loop2"]
    n_msg_thread_prod_bot["msg_thread_prod_bot"]
    n_msg_thread_unknown["msg_thread_unknown"]
    n_msg_thread_work_team["msg_thread_work_team"]
    n_office_to_meeting_room_locked_mail["office_to_meeting_room_locked_mail"]
    n_office_to_meeting_room_locked_turnstile["office_to_meeting_room_locked_turnstile"]
    n_office_to_workspace_locked["office_to_workspace_locked"]
    n_office_turnstile_prompt["office_turnstile_prompt"]
    n_park_bench_interact["park_bench_interact"]
    n_park_bench_main_talk["park_bench_main_talk"]
    n_park_bench_npc_show["park_bench_npc_show"]
    n_park_bin_prompt["park_bin_prompt"]
    n_park_entrance_view["park_entrance_view"]
    n_park_message_where_are_you["park_message_where_are_you"]
    n_park_npc_arrives["park_npc_arrives"]
    n_park_npc_arrives_after_gift["park_npc_arrives_after_gift"]
    n_park_offer_place["park_offer_place"]
    n_park_path_main_talk["park_path_main_talk"]
    n_park_path_npc_show["park_path_npc_show"]
    n_park_path_trees["park_path_trees"]
    n_park_path_walk["park_path_walk"]
    n_park_river_view["park_river_view"]
    n_phone_bank_charge_cafe_coffee_sweet["phone_bank_charge_cafe_coffee_sweet"]
    n_phone_bank_charge_cafe_tea_small["phone_bank_charge_cafe_tea_small"]
    n_phone_bank_charge_cafe_two_coffee["phone_bank_charge_cafe_two_coffee"]
    n_phone_bank_charge_shop_120["phone_bank_charge_shop_120"]
    n_phone_bank_charge_shop_140["phone_bank_charge_shop_140"]
    n_phone_bank_charge_shop_160["phone_bank_charge_shop_160"]
    n_phone_bank_charge_shop_170["phone_bank_charge_shop_170"]
    n_phone_bank_charge_shop_180["phone_bank_charge_shop_180"]
    n_phone_bank_charge_shop_190["phone_bank_charge_shop_190"]
    n_phone_bank_charge_shop_210["phone_bank_charge_shop_210"]
    n_phone_bank_charge_shop_220["phone_bank_charge_shop_220"]
    n_phone_bank_charge_shop_230["phone_bank_charge_shop_230"]
    n_phone_bank_charge_shop_240["phone_bank_charge_shop_240"]
    n_phone_bank_charge_shop_320["phone_bank_charge_shop_320"]
    n_phone_bank_charge_shop_350["phone_bank_charge_shop_350"]
    n_phone_bank_charge_shop_360["phone_bank_charge_shop_360"]
    n_phone_bank_charge_shop_380["phone_bank_charge_shop_380"]
    n_phone_bank_charge_shop_420["phone_bank_charge_shop_420"]
    n_phone_bank_charge_shop_490["phone_bank_charge_shop_490"]
    n_phone_bank_charge_shop_95["phone_bank_charge_shop_95"]
    n_phone_call_seed_sunday_morning["phone_call_seed_sunday_morning"]
    n_phone_mail_seed_sunday_morning["phone_mail_seed_sunday_morning"]
    n_phone_msg_park_arrival_prompt["phone_msg_park_arrival_prompt"]
    n_phone_msg_park_where_reply_bench["phone_msg_park_where_reply_bench"]
    n_phone_msg_park_where_reply_path["phone_msg_park_where_reply_path"]
    n_phone_msg_seed_sunday_morning["phone_msg_seed_sunday_morning"]
    n_phone_msg_sunday_evening_home_thanks["phone_msg_sunday_evening_home_thanks"]
    n_phone_msg_sunday_evening_reply_calm["phone_msg_sunday_evening_reply_calm"]
    n_phone_msg_sunday_evening_reply_warm["phone_msg_sunday_evening_reply_warm"]
    n_phone_msg_sunday_invite_after_coffee["phone_msg_sunday_invite_after_coffee"]
    n_phone_msg_take_phone_sunday_morning["phone_msg_take_phone_sunday_morning"]
    n_phone_sms_seed_sunday_morning["phone_sms_seed_sunday_morning"]
    n_phone_sms_take_phone_sunday_morning["phone_sms_take_phone_sunday_morning"]
    n_phone_sms_tuesday_case_followup["phone_sms_tuesday_case_followup"]
    n_question_reality["question_reality"]
    n_read_entries["read_entries"]
    n_read_journal["read_journal"]
    n_seed_phone_history["seed_phone_history"]
    n_shop_cleaning_supplies_interact["shop_cleaning_supplies_interact"]
    n_shop_cleaning_supplies_pre_date["shop_cleaning_supplies_pre_date"]
    n_shop_cleaning_supplies_with_npc["shop_cleaning_supplies_with_npc"]
    n_shop_counter_interact["shop_counter_interact"]
    n_shop_drinks_interact["shop_drinks_interact"]
    n_shop_drinks_pre_date["shop_drinks_pre_date"]
    n_shop_drinks_with_npc["shop_drinks_with_npc"]
    n_shop_household_goods_interact["shop_household_goods_interact"]
    n_shop_household_goods_pre_date["shop_household_goods_pre_date"]
    n_shop_household_goods_with_npc["shop_household_goods_with_npc"]
    n_shop_paper_goods_interact["shop_paper_goods_interact"]
    n_shop_paper_goods_pre_date["shop_paper_goods_pre_date"]
    n_shop_paper_goods_with_npc["shop_paper_goods_with_npc"]
    n_shop_sign_interact["shop_sign_interact"]
    n_shop_snacks_interact["shop_snacks_interact"]
    n_shop_snacks_pre_date["shop_snacks_pre_date"]
    n_shop_snacks_with_npc["shop_snacks_with_npc"]
    n_shop_window_interact["shop_window_interact"]
    n_sms_service_done["sms_service_done"]
    n_stage_1["stage_1"]
    n_stage_2["stage_2"]
    n_stage_3["stage_3"]
    n_stages_start["stages_start"]
    n_sunday_date_cafe_arrival["sunday_date_cafe_arrival"]
    n_sunday_date_cafe_arrival_after_gift["sunday_date_cafe_arrival_after_gift"]
    n_sunday_date_cafe_settle["sunday_date_cafe_settle"]
    n_sunday_date_go_cafe["sunday_date_go_cafe"]
    n_sunday_date_go_park["sunday_date_go_park"]
    n_sunday_date_map_fallback["sunday_date_map_fallback"]
    n_sunday_date_park_arrival["sunday_date_park_arrival"]
    n_sunday_date_park_settle["sunday_date_park_settle"]
    n_sunday_evening_finish["sunday_evening_finish"]
    n_sunday_evening_home["sunday_evening_home"]
    n_sunday_get_dressed["sunday_get_dressed"]
    n_sunday_gift_react["sunday_gift_react"]
    n_sunday_gift_react_cafe["sunday_gift_react_cafe"]
    n_sunday_gift_react_park["sunday_gift_react_park"]
    n_sunday_home_after_date_router["sunday_home_after_date_router"]
    n_sunday_home_too_early["sunday_home_too_early"]
    n_sunday_send_messenger_invite["sunday_send_messenger_invite"]
    n_sunday_shop_arrival["sunday_shop_arrival"]
    n_sunday_shop_arrival_pre_date["sunday_shop_arrival_pre_date"]
    n_sunday_shop_arrival_with_npc["sunday_shop_arrival_with_npc"]
    n_sunday_shop_settle["sunday_shop_settle"]
    n_sunday_shop_street_arrival["sunday_shop_street_arrival"]
    n_sunday_sleep_in_bed["sunday_sleep_in_bed"]
    n_sunday_start_splash["sunday_start_splash"]
    n_sunday_viewpoint_arrival["sunday_viewpoint_arrival"]
    n_sunday_viewpoint_settle["sunday_viewpoint_settle"]
    n_take_kitchen_apple["take_kitchen_apple"]
    n_take_mug["take_mug"]
    n_take_park_trash_cup["take_park_trash_cup"]
    n_take_phone["take_phone"]
    n_take_toothbrush["take_toothbrush"]
    n_take_toothpaste["take_toothpaste"]
    n_talk_to_someone["talk_to_someone"]
    n_tue_home_bed["tue_home_bed"]
    n_tue_home_bedroom_desk["tue_home_bedroom_desk"]
    n_tue_home_bedroom_intro["tue_home_bedroom_intro"]
    n_tue_home_check_phone["tue_home_check_phone"]
    n_tue_home_get_ready["tue_home_get_ready"]
    n_tue_home_hall_intro["tue_home_hall_intro"]
    n_tue_home_hall_mirror["tue_home_hall_mirror"]
    n_tue_home_kitchen_coffee["tue_home_kitchen_coffee"]
    n_tue_home_kitchen_coffee_after["tue_home_kitchen_coffee_after"]
    n_tue_home_kitchen_intro["tue_home_kitchen_intro"]
    n_tue_home_kitchen_water["tue_home_kitchen_water"]
    n_tue_home_kitchen_window["tue_home_kitchen_window"]
    n_tue_home_leave_apartment["tue_home_leave_apartment"]
    n_tue_home_leave_apartment_locked["tue_home_leave_apartment_locked"]
    n_tue_home_wash_up["tue_home_wash_up"]
    n_tue_rooftop_ending_npc["tue_rooftop_ending_npc"]
    n_tue_rooftop_ending_system["tue_rooftop_ending_system"]
    n_tue_rooftop_ending_true["tue_rooftop_ending_true"]
    n_tue_rooftop_entry["tue_rooftop_entry"]
    n_tue_rooftop_iter001_entry["tue_rooftop_iter001_entry"]
    n_tue_rooftop_iter001_finish["tue_rooftop_iter001_finish"]
    n_tue_rooftop_iter001_realization["tue_rooftop_iter001_realization"]
    n_tue_rooftop_iter001_talk["tue_rooftop_iter001_talk"]
    n_tue_rooftop_loop_entry["tue_rooftop_loop_entry"]
    n_tue_rooftop_loop_route["tue_rooftop_loop_route"]
    n_tue_rooftop_loop_signal["tue_rooftop_loop_signal"]
    n_tue_rooftop_loop_talk["tue_rooftop_loop_talk"]
    n_tue_route_after_review["tue_route_after_review"]
    n_tue_route_ask_npc["tue_route_ask_npc"]
    n_tue_route_entry["tue_route_entry"]
    n_tue_route_office_return["tue_route_office_return"]
    n_tue_route_read_appeal["tue_route_read_appeal"]
    n_tue_route_read_log["tue_route_read_log"]
    n_tue_route_review_options["tue_route_review_options"]
    n_tue_route_to_rooftop["tue_route_to_rooftop"]
    n_tuesday_morning_start["tuesday_morning_start"]
    n_use_coffee_setup_no_mug["use_coffee_setup_no_mug"]
    n_view_binoculars_interact["view_binoculars_interact"]
    n_view_city_interact["view_city_interact"]
    n_view_corner_bench_interact["view_corner_bench_interact"]
    n_view_corner_glass_interact["view_corner_glass_interact"]
    n_view_corner_main_talk["view_corner_main_talk"]
    n_view_corner_planter_interact["view_corner_planter_interact"]
    n_view_railing_interact["view_railing_interact"]
    n_window_view["window_view"]
    n_work_desk_case_file_prompt["work_desk_case_file_prompt"]
    n_work_desk_done["work_desk_done"]
    n_work_desk_needs_case_file["work_desk_needs_case_file"]
    n_work_desk_read_mail["work_desk_read_mail"]
    n_workspace_to_meeting_room_locked["workspace_to_meeting_room_locked"]
    n_write_entry["write_entry"]
    end

    n_loop_entry -->|"Начать день"| n_day_start
    n_loop_entry -->|"Посмотреть в окно"| n_window_view
    n_choose_character -->|"Артём"| n_sunday_start_splash
    n_choose_character -->|"Мила"| n_sunday_start_splash
    n_sunday_evening_home -->|"Ответить тепло"| n_sunday_evening_finish
    n_sunday_evening_home -->|"Ответить спокойно"| n_sunday_evening_finish
    n_sunday_evening_home -->|"Не отвечать сразу"| n_sunday_evening_finish
    n_park_bench_main_talk --> n_sunday_date_park_settle
    n_park_bench_main_talk -->|"Пошутить про прогулку как план"| n_sunday_date_park_settle
    n_park_bench_main_talk -->|"Признаться, что парк казался проще"| n_sunday_date_park_settle
    n_park_path_main_talk --> n_sunday_date_park_settle
    n_park_path_main_talk -->|"Подстроиться под общий темп"| n_sunday_date_park_settle
    n_park_path_main_talk -->|"Признаться, что так меньше давления"| n_sunday_date_park_settle
    n_cafe_corner_main_talk --> n_sunday_date_cafe_settle
    n_cafe_corner_main_talk -->|"Пошутить про совместимость по заказу"| n_sunday_date_cafe_settle
    n_cafe_corner_main_talk -->|"Признаться, что кафе казалось безопасны…"| n_sunday_date_cafe_settle
    n_sunday_shop_arrival_with_npc -->|"Взять воду на двоих"| n_sunday_shop_settle
    n_sunday_shop_arrival_with_npc -->|"Взять что-нибудь сладкое"| n_sunday_shop_settle
    n_sunday_shop_arrival_with_npc --> n_sunday_shop_settle
    n_shop_drinks_with_npc -->|"Взять воду на двоих"| n_sunday_shop_settle
    n_shop_drinks_with_npc -->|"Взять холодный чай"| n_sunday_shop_settle
    n_shop_snacks_with_npc -->|"Взять что-нибудь сладкое"| n_sunday_shop_settle
    n_shop_snacks_with_npc --> n_sunday_shop_settle
    n_view_corner_main_talk --> n_sunday_viewpoint_settle
    n_view_corner_main_talk -->|"Пошутить про смотровую как серьёзный фи…"| n_sunday_viewpoint_settle
    n_view_corner_main_talk -->|"Признаться, что не хотелось сразу домой"| n_sunday_viewpoint_settle
    n_mon_commute_entry -->|"Идти на автомате"| n_mon_commute_walk_auto
    n_mon_commute_entry -->|"Замедлиться и заметить маршрут"| n_mon_commute_walk_observe
    n_mon_commute_entry -->|"Держать ровный темп"| n_mon_commute_walk_steady
    n_mon_office_npc_greeting -->|"Пошутить про рабочую версию себя"| n_mon_office_task_intro
    n_mon_office_npc_greeting -->|"Сказать, что всё слишком аккуратно"| n_mon_office_npc_strange
    n_mon_office_npc_greeting -->|"Сразу открыть кейс"| n_mon_office_task_intro
    n_mon_office_core_choice -->|"Согласиться со стандартным решением"| n_mon_office_manual_standard
    n_mon_office_core_choice -->|"Запросить недостающие данные"| n_mon_office_clarify
    n_mon_office_core_choice -->|"Остановить автоприменение"| n_mon_office_stop_auto
    n_tue_route_review_options -->|"Посмотреть лог решения"| n_tue_route_read_log
    n_tue_route_review_options --> n_tue_route_ask_npc
    n_tue_route_review_options -->|"Открыть карточку апелляции"| n_tue_route_read_appeal
    n_tue_rooftop_loop_talk -->|"Держаться за человека рядом"| n_tue_rooftop_loop_route
    n_tue_rooftop_loop_talk -->|"Держаться за логику системы"| n_tue_rooftop_loop_route
    n_tue_rooftop_loop_talk --> n_tue_rooftop_ending_true
    n_find_clue -->|"Осмотреться"| n_look_around
    n_find_clue -->|"Поговорить с кем-то"| n_talk_to_someone
    n_question_reality -->|"Это правда происходит?"| n_doubt
    n_question_reality -->|"Петля реальна"| n_accept
    n_read_journal -->|"Прочитать записи"| n_read_entries
    n_read_journal -->|"Вернуться"| n_go_back
    n_msg_thread_mila_iter1 -->|"«А тебе куда хочется?»"| n_msg_npc_place_sent
    n_msg_thread_mila_iter1 -->|"«Давай в кафе. Спокойно посидим.»"| n_msg_npc_place_sent
    n_msg_thread_mila_iter1 -->|"«Давай в парк у реки. Хочется пройтись.»"| n_msg_npc_place_sent
    n_msg_thread_artem_iter1 -->|"«А тебе куда хочется?»"| n_msg_npc_place_sent
    n_msg_thread_artem_iter1 -->|"«Давай в кафе. Спокойно посидим.»"| n_msg_npc_place_sent
    n_msg_thread_artem_iter1 -->|"«Давай в парк у реки. Хочется пройтись.»"| n_msg_npc_place_sent
    n_msg_thread_mila_loop2 -->|"«Очень смешно.»"| n_msg_mila_loop2_place_pressure
    n_msg_thread_mila_loop2 -->|"«Ты уже писала это.»"| n_msg_mila_loop2_place_pressure
    n_msg_thread_mila_loop2 -->|"«Ок. Давай встретимся.»"| n_msg_mila_loop2_place_choice
    n_msg_mila_loop2_place_pressure -->|"«Нет. Но давай всё равно встретимся.»"| n_msg_mila_loop2_place_choice
    n_msg_mila_loop2_place_pressure -->|"«Если это розыгрыш — я хочу увидеть лиц…"| n_msg_mila_loop2_place_choice
    n_msg_mila_loop2_place_choice -->|"«Давай в кафе. Спокойно посидим.»"| n_msg_npc_place_sent
    n_msg_mila_loop2_place_choice -->|"«Давай в парк у реки. Хочется пройтись.»"| n_msg_npc_place_sent
    n_msg_thread_artem_loop2 -->|"«Очень смешно.»"| n_msg_artem_loop2_place_pressure
    n_msg_thread_artem_loop2 -->|"«Ты уже писал это.»"| n_msg_artem_loop2_place_pressure
    n_msg_thread_artem_loop2 -->|"«Ок. Давай встретимся.»"| n_msg_artem_loop2_place_choice
    n_msg_artem_loop2_place_pressure -->|"«Нет. Но давай всё равно встретимся.»"| n_msg_artem_loop2_place_choice
    n_msg_artem_loop2_place_pressure -->|"«Если это розыгрыш — я хочу увидеть лиц…"| n_msg_artem_loop2_place_choice
    n_msg_artem_loop2_place_choice -->|"«Давай в кафе. Спокойно посидим.»"| n_msg_npc_place_sent
    n_msg_artem_loop2_place_choice -->|"«Давай в парк у реки. Хочется пройтись.»"| n_msg_npc_place_sent
    n___start --> n_choose_character
```
